version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  ch_client:
    image: yandex/clickhouse-client
  ch_aws_1:
    build:
      context: .
      dockerfile: Dockerfile.ch
      args:
        SHARD_CONFIG: 'ch_aws_1_config.xml'
    depends_on:
      - zookeeper
    ports:
      - 8811:8123
      - 9011:9000
    volumes:
      - ./ch_aws_1_volume:/var/lib/clickhouse
  ch_aws_2:
    build:
      context: .
      dockerfile: Dockerfile.ch
      args:
        SHARD_CONFIG: 'ch_aws_2_config.xml'
    depends_on:
      - zookeeper
    ports:
      - 8812:8123
      - 9012:9000
    volumes:
      - "./ch_aws_2_volume:/var/lib/clickhouse"
  ch_hetzner_1:
    build:
      context: .
      dockerfile: Dockerfile.ch
      args:
        SHARD_CONFIG: 'ch_hetzner_1_config.xml'
    depends_on:
      - zookeeper
    ports:
      - 8813:8123
      - 9013:9000
    volumes:
      - "./ch_hetzner_1_volume:/var/lib/clickhouse"
  ch_hetzner_2:
    build:
      context: .
      dockerfile: Dockerfile.ch
      args:
        SHARD_CONFIG: 'ch_hetzner_2_config.xml'
    depends_on:
      - zookeeper
    ports:
      - 8814:8123
      - 9014:9000
    volumes:
      - "./ch_hetzner_2_volume:/var/lib/clickhouse"
